name: build-release-sql

on:
  push:
    tags:
      - 'qa-*'
      - 'prod-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identify current and previous tag
        id: taginfo
        run: |
          CUR_TAG="${GITHUB_REF#refs/tags/}"
          echo "CURRENT_TAG=$CUR_TAG" >> $GITHUB_ENV

          PREFIX=$(echo "$CUR_TAG" | cut -d'-' -f1)
          PREV_TAG=$(git tag --list "${PREFIX}-*" | sort | grep -v "$CUR_TAG" | tail -1 || true)
          echo "PREVIOUS_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Get all changed .sql files
        run: |
          if [ -z "$PREVIOUS_TAG" ]; then
            git diff --name-only HEAD -- changes/*.sql > list.txt
          else
            git diff --name-only "$PREVIOUS_TAG"...HEAD -- changes/*.sql > list.txt
          fi

          echo "Changed files:"
          cat list.txt

      - name: Build release SQL file
        run: |
          OUTFILE="releases/${CURRENT_TAG}.sql"
          echo "-- auto release: $CURRENT_TAG" > "$OUTFILE"
          echo "" >> "$OUTFILE"

          while read -r file; do
            if [ -f "$file" ]; then
              echo "-- $file" >> "$OUTFILE"
              cat "$file" >> "$OUTFILE"
              echo -e "\n" >> "$OUTFILE"
            fi
          done < list.txt

      - name: Commit release file to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto release ${{ env.CURRENT_TAG }}"
          file_pattern: "releases/*.sql"
          branch: main
