name: build-release-sql

on:
  push:
    tags:
      - 'qa-*'
      - 'prod-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine context
        id: context
        run: |
          CUR_TAG="${GITHUB_REF#refs/tags/}"
          echo "CURRENT_TAG=$CUR_TAG" >> $GITHUB_ENV

          PREFIX=$(echo "$CUR_TAG" | cut -d'-' -f1)
          echo "PREFIX=$PREFIX" >> $GITHUB_ENV

          if [ "$PREFIX" = "qa" ]; then
            PREV_TAG=$(git tag --list 'qa-*' --sort=-creatordate | grep -v "$CUR_TAG" | head -1)
          elif [ "$PREFIX" = "prod" ]; then
            PREV_TAG=$(git tag --list 'prod-*' --sort=-creatordate | grep -v "$CUR_TAG" | head -1)
            QA_BASE=$(git tag --list 'qa-*' --sort=-creatordate | head -1)
            echo "QA_BASE=$QA_BASE" >> $GITHUB_ENV
          fi

          echo "PREVIOUS_TAG=$PREV_TAG" >> $GITHUB_ENV

          if [ -z "$PREV_TAG" ]; then
            echo "FIRST_RELEASE=true" >> $GITHUB_ENV
          else
            echo "FIRST_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Build release SQL file
        run: |
          OUTFILE="releases/${CURRENT_TAG}.sql"
          echo "/********************************************/" > "$OUTFILE"
          echo "-- AUTO RELEASE: ${CURRENT_TAG}" >> "$OUTFILE"
          echo "-- PREFIX: ${PREFIX}" >> "$OUTFILE"
          echo "-- BASE: ${PREVIOUS_TAG}" >> "$OUTFILE"
          echo "/********************************************/" >> "$OUTFILE"

          echo "----------------------------------------------" >> "$OUTFILE"
          echo "-- SECTION: MIGRATIONS (changes/)" >> "$OUTFILE"
          echo "----------------------------------------------" >> "$OUTFILE"

          if [ "$PREFIX" = "qa" ]; then
            RANGE="$PREVIOUS_TAG...HEAD"
          elif [ "$PREFIX" = "prod" ]; then
            RANGE="$PREVIOUS_TAG...$QA_BASE"
          fi

          CHANGED_FILES=$(git diff --name-only --diff-filter=AM $RANGE -- changes/**/*.sql || true)

          for f in $CHANGED_FILES; do
            if [ -f "$f" ]; then
              echo "-- FILE: $f" >> "$OUTFILE"
              cat "$f" >> "$OUTFILE"
              echo -e "\n\n" >> "$OUTFILE"
            fi
          done

          echo "----------------------------------------------" >> "$OUTFILE"
          echo "-- SECTION: SCHEMA CHANGES" >> "$OUTFILE"
          echo "----------------------------------------------" >> "$OUTFILE"

          if [ "$FIRST_RELEASE" = "true" ]; then
            for f in $(find schema -type f -name "*.sql" || true); do
              echo "-- SCHEMA OBJECT: $f" >> "$OUTFILE"
              cat "$f" >> "$OUTFILE"
              echo -e "\n\n" >> "$OUTFILE"
            done
          else
            NEW_SCHEMA=$(git diff --name-status $RANGE -- schema/**/*.sql | grep '^A' | cut -f2 || true)
            for f in $NEW_SCHEMA; do
              if [ -f "$f" ]; then
                echo "-- NEW OBJECT: $f" >> "$OUTFILE"
                cat "$f" >> "$OUTFILE"
                echo -e "\n\n" >> "$OUTFILE"
              fi
            done

            echo "-- MODIFIED OBJECTS (AS COMMENTS)" >> "$OUTFILE"
            MOD_SCHEMA=$(git diff --name-status $RANGE -- schema/**/*.sql | grep '^M' | cut -f2 || true)
            for f in $MOD_SCHEMA; do
              echo "-- MODIFIED: $f" >> "$OUTFILE"
              echo "-- BEGIN DIFF" >> "$OUTFILE"
              git diff $RANGE -- "$f" | sed 's/^/-- /' >> "$OUTFILE"
              echo "-- END DIFF" >> "$OUTFILE"
              echo -e "\n\n" >> "$OUTFILE"
            done
          fi

      - name: Commit release file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto release ${{ env.CURRENT_TAG }}"
          file_pattern: "releases/*.sql"
          branch: main
